### ISSUE TITLE
undefined method 'authenticates_with_sorcery!'

### ISSUE THREAD

**Issue by thepixelmonk** [NoamB/sorcery-example-app#2]
When creating a new user the password seems to just be stored as plaintext. I got the feeling that sorcery wasn't processing it for some reason. I checked over the example app and saw `authenticates_with_sorcery!` in the user class, but I just get an undefined method error when adding it to my class. I also have `config.user_class = User` in my initializer. Any ideas?

**Comment by spaudanjo** [comment]
could you give a hint for the solution? :-)

**Comment by bicepjai** [comment]
whats the solution for this issue ? it wud be appreciated if the answer is posted !

**Comment by thepixelmonk** [comment]
never found out myself, just went back to devise =/

**Comment by thepixelmonk** [comment]
I don't know why this issue keeps appearing I tried sorcery again recently but same thing.

**Comment by bicepjai** [comment]
i enabled 
Rails.application.config.sorcery.submodules = [:http_basic_auth] 
in sorcery.rb and it worked fine for me. i dnt know the reason, i just tried.
im using rails 3.1.3

**Comment by nachbar** [comment]
I don't know what your setup is, but I was getting this error in a test rails app using MongoMapper and Sorcery, when I had not excluded ActiveRecord.

When I set up my app to use MongoMapper but exclude ActiveRecord (as detailed at http://mongomapper.com/documentation/getting-started/rails.html, but specifically using the --skip-active-record option to rails new), the problem went away (although I did get an error that bcrypt was not available: 

```
LoadError: no such file to load -- bcrypt
```

That was resolved by putting 

```
gem "bcrypt-ruby", :require => "bcrypt"
```

in my Gemfile)
