### ISSUE TITLE
undefined method `auto_login' for nil:NilClass

### ISSUE THREAD

**Issue by ghost** [NoamB/sorcery-example-app#3]
Guess I must be missing something here. I have a simple integration spec from which I'm trying to login a user. 

``` ruby
let(:user) { Factory(:user, :email => "user@example.com", :password => "secret", :password_confirmation => "secret" ) }
```

and then in:

``` ruby
background do            
  login_user(user)       
  ....
end
```

when the spec is run:

``` bash
Failure/Error: login_user(user)
     NoMethodError:
       undefined method `auto_login' for nil:NilClass
     # ./spec/requests/deleting_entries_spec.rb:15:in `block (2 levels) in <top (required)>'
```

**Comment by NoamB** [comment]
auto_login is called on a controller instance.
You have no controller instance in your context, so auto_login is called on nil.

**Comment by ZachBeta** [comment]
New to testing.
Having trouble figuring out how to pull a controller instance into the context.

Any docs out there?

**Comment by ZachBeta** [comment]
https://github.com/NoamB/sorcery/issues/61
